### ISSUE TITLE
"Unfortunately no metabolites in your dataset were predicted based on metabolic potential"

### ISSUE THREAD

**Issue by Ewandson** [borenstein-lab/mimosa2#7]
Hello Cecilia,

    I am having an issue with a custom database where I got the following message:

```
Error in run_mimosa2("configuration_table.txt", make_plots = T, save_plots = T, :
Unfortunately no metabolites in your dataset were predicted based on metabolic potential. Try an expanded network model or use get_species_cmp_scores() to obtain CMP scores without comparing.
```
![Screenshot 2023-03-21 at 11 29 21 AM](https://user-images.githubusercontent.com/30441571/226693868-b2ca8892-7c7e-439c-9473-86ae2aa53ece.png)

  I built the database based on the instructions you sent us by email and I'm not sure if the problem is related to it or maybe another thing. Could you please help us with it?

I'll let the dropbox link below so you'll be able to check the files, the database, and the R script I'm using to run Mimosa2. 

We appreciate any help.

Dropbox: [link](https://www.dropbox.com/sh/4jac4o70l5j99v7/AADaFiXz9tO4SlUMrQUYBhW3a?dl=0)

**Comment by cnoecker** [comment]
Hi,
Thanks for sending your data files. I caught a couple small things in your configuration table:
- Change the "T" in the second column of your configuration table to actually say "TRUE". 
- Change "rank_based" to "rankBased". 

But the main issue is with your network tables. The MIMOSA2 code is set up to only know how to work with BIGG/AGORA metabolite IDs in the format "nadp[c]" (i.e. compoundID[compartment]) , and your models have metabolites in the format "nadp_c" (or compoundID_compartment). So if you change underscores to brackets in all your network models, it will then be able to compare those with your metabolite data and you should be good to go. (You can do this with the following snippet of code in R, where network is the reaction network for a particular species: 
`library(data.table)`
`network <- data.table(network)`
`network[,Reac:=gsub("_([[:alpha:]])$", "\\[\\1\\]",Reac)]`
`network[,Prod:=gsub("_([[:alpha:]])$", "\\[\\1\\]",Prod)]`

Also, if you are working with a synthetic community (as I think we talked about), I think something strange might be happening with your mapping between ASVs and models, because only 9 strains are getting added with the model. If that doesn't sound right, you may want to check the alignments between your ASVs and the database ASVs.

I hope that helps!

**Comment by Ewandson** [comment]
thank you very much for addressing my questions, I'll implement your suggestions. Thanks

**Comment by Ewandson** [comment]
Update: after doing the modifications in the configuration file and also fixing the metabolites IDs the pipeline ran perfectly. Thank you very much, Cecilia!

**Comment by cnoecker** [comment]
Glad to hear it!
